# Generated by Django 4.2 on 2023-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dog_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.CharField(max_length=4),
        ),
    ]
