# Generated by Django 4.2 on 2023-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_breed_alter_dog_age_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=100),
        ),
    ]
